// API URL
export const API_URL = (process.env.REACT_APP_NODE_ENV !== 'production') ? process.env.REACT_APP_API_LOCAL_URL : process.env.REACT_APP_API_LIVE_URL ;

// SETTING
export const GET_SETTING ='GET_SETTING'

// AUTH
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const GET_PROFILE = 'GET_PROFILE';

// ALERT
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// USER
export const GET_USER = 'GET_USER';
export const GET_USERS = 'GET_USERS';
export const UPDATE_USER = 'UPDATE_USER';

// STAGE
export const GET_STAGES = 'GET_STAGES'
export const UPDATE_STAGE = 'UPDATE_STAGE'
export const SORT_STAGE_CARD = 'SORT_STAGE_CARD'
export const FILTER_STAGE_CARD = 'FILTER_STAGE_CARD'
export const SET_STAGE_FILTER_FIELDS = 'SET_STAGE_FILTER_FIELDS'

// CUSTOM TABLE FIELDS
export const GET_ORGANISATION_FIELDS = 'GET_ORGANISATION_FIELDS';
export const GET_CONTACT_FIELDS = 'GET_CONTACT_FIELDS';
export const GET_DEAL_FIELDS = 'GET_DEAL_FIELDS';
export const GET_ORGANIZATION_CONTACTS = 'GET_ORGANIZATION_CONTACTS';

// ORGANISATION
export const ADD_ORGANISATION = 'ADD_ORGANISATION';
export const UPDATE_ORGANISATION = 'UPDATE_ORGANISATION';
export const GET_ORGANISATIONS = 'GET_ORGANISATIONS';
export const GET_ORGANISATION = 'GET_ORGANISATION';
export const DELETE_ORGANISATION = 'DELETE_ORGANISATION';

export const ADD_ORGANISATION_NOTES = 'ADD_ORGANISATION_NOTES';
export const GET_ORGANISATION_NOTES = 'GET_ORGANISATION_NOTES';
export const GET_ORGANISATION_LOGS = 'GET_ORGANISATION_LOGS';
export const REDIRECT_ORGANISATION = 'REDIRECT_ORGANISATION';
export const SORT_ORG_FIELD = 'SORT_ORG_FIELD';
export const PAGINATE_ORGANIZATIONS = 'PAGINATE_ORGANIZATIONS';
export const APPEND_ORGANIZATIONS = 'APPEND_ORGANIZATIONS';
export const SET_ORGANISATION_FILTER_FIELDS = 'SET_ORGANISATION_FILTER_FIELDS';
export const NEW_CONTACT = 'NEW_CONTACT';

// CONTACT
export const ADD_CONTACT = 'ADD_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const GET_CONTACTS = 'GET_CONTACTS';
export const GET_CONTACT = 'GET_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';

export const ADD_CONTACT_NOTES = 'ADD_CONTACT_NOTES';
export const GET_CONTACT_NOTES = 'GET_CONTACT_NOTES';
export const GET_CONTACT_LOGS = 'GET_CONTACT_LOGS';
export const REDIRECT_CONTACT = 'REDIRECT_CONTACT';
export const SORT_CONTACT_FIELD = 'SORT_CONTACT_FIELD';
export const PAGINATE_CONTACTS = 'PAGINATE_CONTACTS';
export const IMPORT_CONTACTS = 'IMPORT_CONTACTS';
export const NEW_DEAL = 'NEW_DEAL';
export const APPEND_CONTACTS = 'APPEND_CONTACTS';
export const SET_CONTACT_FILTER_FIELDS = 'SET_CONTACT_FILTER_FIELDS';

// DEAL
export const ADD_DEAL = 'ADD_DEAL';
export const UPDATE_DEAL = 'UPDATE_DEAL';
export const GET_DEALS = 'GET_DEALS';
export const GET_DEAL = 'GET_DEAL';
export const DELETE_DEAL = 'DELETE_DEAL';

export const ADD_DEAL_NOTES = 'ADD_DEAL_NOTES';
export const GET_DEAL_NOTES = 'GET_DEAL_NOTES';
export const GET_DEAL_LOGS = 'GET_DEAL_LOGS';
export const REDIRECT_DEAL = 'REDIRECT_DEAL';
export const UPDATE_DEAL_ACTION = 'UPDATE_DEAL_ACTION';
export const GET_WON_DEAL = 'GET_WON_DEAL';
export const EMPTY_SINGLE_DEAL = 'EMPTY_SINGLE_DEAL';
export const SORT_DEAL_FIELD = 'SORT_DEAL_FIELD';
export const PAGINATE_DEALS = 'PAGINATE_DEALS';
export const GET_DEAL_LOST_REASONS = 'GET_DEAL_LOST_REASONS';
export const APPEND_DEALS = 'APPEND_DEALS';
export const SET_DEAL_FILTER_FIELDS = 'SET_DEAL_FILTER_FIELDS';
export const GET_CANCEL_DEALS = 'GET_CANCEL_DEALS';
export const APPEND_CANCEL_DEALS = 'APPEND_CANCEL_DEALS';
export const DELETE_CANCEL_DEAL = 'DELETE_CANCEL_DEAL';

// NOTIFICATION
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_UNREAD_NOTIFICATIONS = 'GET_UNREAD_NOTIFICATIONS';
export const GET_READ_NOTIFICATIONS = 'GET_READ_NOTIFICATIONS';

// THEME
export const APPLY_THEME = 'APPLY_THEME ';

// REPORT
export const GET_STAGE_CATEGORIES = 'GET_STAGE_CATEGORIES ';
export const GET_PENDING_DEAL_VALUES_WITH_STAGES = 'GET_PENDING_DEAL_VALUES_WITH_STAGES ';
export const GET_WON_LOST_DEAL_VALUES = 'GET_WON_LOST_DEAL_VALUES ';
export const GET_CANCELLED_DEAL_VALUES = 'GET_CANCELLED_DEAL_VALUES ';
export const GET_NET_DEAL_VALUES = 'GET_NET_DEAL_VALUES ';

// LOADER
export const SHOW_LOADER = 'SHOW_LOADER ';
export const HIDE_LOADER = 'HIDE_LOADER ';