module.exports = {
	'User': require('./user.model'),
	'Country': require('./country.model'),
	'Industry': require('./industry.model'),
	'Cluster': require('./cluster.model'),
	'Stage': require('./stage.model'),
	'CustomTable': require('./custom_table.model'),
	'CustomTableFieldValue': require('./custom_field_value.model'),
	'Organization': require('./organization.model'),
	'Log': require('./log.model'),
	'Note': require('./note.model'),
	'Contact': require('./contact.model'),
	'Deal': require('./deal.model'),
	'Setting':  require('./setting.model') ,
	'DealStage': require('./deal_stage.model'),
	'DealAction': require('./deal_action.model'),
	'Notification': require('./notification.model'),
	'Reason': require('./reason.model'),
};